"""Define constants for the OpenADR VEN component."""
DOMAIN = "powershaper"
ATTR_LAST_DATA = "last_data"
CONF_APP_KEY = "app_key"
DATA_CLIENT = "data_client"
TOPIC_UPDATE = "update"
DATA_CONFIG = "config"
OADR_AGENT = "oadr_agent"
POWERSHAPER_SERVICES = "powershaper_services"
SERVICE_TELEMETRY = "add_openadr_telemetry"
SERVICE_GET_TELEMETRY = "get_openadr_telemetry_json_from_endpoint"


VEN_ID = "ven_id"
VEN_NAME = "ven_name"
VTN_ID = "vtn_id"
VTN_ADDRESS = "vtn_address"
SEND_REG = "send_registration"
SECURITY_LEVEL = "security_level"
POLL_INTERVAL_SECS = "poll_interval_secs"
LOG_XML = "log_xml"
OPT_TIMEOUT_SECS = "opt_timeout_secs"
OPT_DEFAULT_DECISION = "opt_default_decision"
REQUEST_EVENTS_ON_STARTUP = "request_events_on_startup"
REPORT_PARAMETERS = "report_parameters"
CLIENT_PEM_BUNDLE_FILEPATH = "client_pem_bundle_filepath"
CA_CERT_FILEPATH = "ca_cert_filepath"
CA_CERT_URL = "ca_cert_url"
DB_FILEPATH = "db_filepath"
HUB_HEMS_REGISTRATION_URL = "hub_hems_registration_url"
INSTALLATION_SHORTCODE = "installation_shortcode"
BINARY_SENSOR_NAME = "DR Event In Progress?"
